### ISSUE TITLE
CUDA Error: no CUDA-capable device is detected 

### ISSUE THREAD

**Issue by Shrunoti** [vjrantal/iot-edge-darknet-module#8]
Hi,

I am running the docker image on Nvidia Jetson TX2 with 3.2.1 Jetpack
I am getting following error after -$ sudo docker run vjrantal/iot-edge-darknet-module

`layer     filters    size              input                output
    0 python: ./src/cuda.c:36: check_error: Assertion '0' failed.
CUDA Error: no CUDA-capable device is detected`

According to my knowledge CUDA is installed properly. 
The CUDA version is 9.0

**Comment by vjrantal** [comment]
@Shrunoti Could you check this solution https://github.com/vjrantal/iot-edge-darknet-module/issues/6#issuecomment-393755057 and let me know if that fixes it for you.

**Comment by snsguest** [comment]
yes, that fixed the problem. Thank you
